baseURL = "https://mmanuelubah.netlify.app/"
title = "mmanuelubah"
languageCode = "en-us"
theme = "hello-friend-ng"
pagination.pagerSize = 10

# Theme Parameters
[params]
  title = "mmanuelubah"
  description = "MindOnChain is a blog that explores blockchain analytics, airdrops, and decentralized innovation — written by Emmanuel."
  avatar = "images/Avatar.png"                  # Path: /static/images/Avatar.png
  enableSharingButtons = true
  enableGlobalLanguageMenu = true
  enableThemeToggle = true
  defaultTheme = "dark"
  showPostsOnHomePage = true
  numberOfPostsOnHomePage = 3

[build]
  writeStats = true

# Logo
[params.logo]
  logoHomeLink = "/"
  logoImage = "images/IMG_4493.jpeg"   # Path: /static/images/favicon-logo-96x96.png

# Favicon
[params.assets]
  favicon = "images/Avatar.png"                # Path: /static/images/favicon.ico

# Footer Section
[params.footer]
  copyright = "© 2025 Emmanuel"

# Social Links
[params.social]
  github = "https://github.com/mmanuelubah"
  linkedin = "https://www.linkedin.com/in/chinaza-ubanatu-05a983184/"
  twitter = "https://x.com/mmanuelubah"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu Navigation
[menu]

